spring:
  application:
    name: project_service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgresql-cluster:5432/appdata
    username: baseuser
    password: aDHqf7ghloP=
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
