spring:
  datasource:
    url: jdbc:postgresql://postgresql-cluster.cnpg-system.svc.cluster.local:5432/appdata
    username: baseuser
    password: aDHqf7ghloP=
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect